# Generated by Django 3.1.4 on 2020-12-19 07:37

from django.db import migrations, models
import observe.validators


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylist',
            name='UploadedFile',
            field=models.FileField(max_length=500, upload_to='lists/', validators=[observe.validators.validate_file_extension], verbose_name='Upload Inventory Listing'),
        ),
    ]
