# Generated by Django 3.1.4 on 2020-12-19 12:09

from django.db import migrations, models
import observe.validators


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0004_auto_20201219_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylist',
            name='UploadedFile',
            field=models.FileField(max_length=500, upload_to='file_upload_location', validators=[observe.validators.validate_file_extension], verbose_name='Upload Inventory Listing'),
        ),
    ]
