# Generated by Django 3.1.4 on 2020-12-21 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0006_auto_20201219_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=150)),
                ('product_category', models.CharField(max_length=150)),
                ('product_description', models.CharField(max_length=150)),
                ('quantity_per_client', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_per_counter', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('quantity_difference', models.FloatField()),
            ],
        ),
    ]
