# Generated by Django 3.1.4 on 2020-12-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0007_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='product_image_1',
            field=models.ImageField(default='files', max_length=500, upload_to='Inventory_Images_from_SKU_Model', verbose_name='Upload Image'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Inventory_Images_from_Image_Model')),
                ('default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observe.sku')),
            ],
        ),
    ]
