# Generated by Django 3.1.4 on 2020-12-22 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0008_auto_20201222_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='default',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='product_image_1',
        ),
    ]
