# Generated by Django 3.1.4 on 2020-12-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observe', '0009_auto_20201222_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='comment',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
